### ISSUE TITLE
Error when trying to execute

### ISSUE THREAD

**Issue by s7relok** [Pirionfr/pyLinky#19]
Hello,

I installed the plugin, both with pip3 and manually, and I have this error.

`Traceback (most recent call last):
  File "/usr/local/bin/pylinky", line 11, in <module>
    load_entry_point('pylinky==0.3.0', 'console_scripts', 'pylinky')()
  File "/usr/local/lib/python3.5/dist-packages/pylinky-0.3.0-py3.5.egg/pylinky/main.py", line 27, in main
  File "/usr/local/lib/python3.5/dist-packages/pylinky-0.3.0-py3.5.egg/pylinky/client.py", line 202, in get_data
  File "/usr/local/lib/python3.5/dist-packages/pylinky-0.3.0-py3.5.egg/pylinky/client.py", line 142, in format_data
AttributeError: 'NoneType' object has no attribute 'get'`

Can someone help me?

**Comment by Pirionfr** [comment]
do you have the pb with v0.2.1 or v0.1.8 ?

**Comment by s7relok** [comment]
I did a git clone, so the 0.2.1 I think

**Comment by Pirionfr** [comment]
no you are on 0.3.0
do a pip install pyplinky==0.2.1
and do pylinky -u \<USERNAME\> -p \<PASSWORD\>
if it now work do 

do a pip install pyplinky==0.1.8
and do pylinky -u \<USERNAME\> -p \<PASSWORD\>
