### ISSUE TITLE
NoneType object has no attribute 'post'

### ISSUE THREAD

**Issue by CygaLV** [Pirionfr/pyLinky#20]
PyLinky version : latest (0.3.1 ? ; anyway, manually updated yesterday)
Platform: Raspberry Pi

I've got the following error at first run:

`019-03-02 21:41:41 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform linky Traceback (most recent call last): File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform SLOW_SETUP_MAX_WAIT, loop=hass.loop)

File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for return fut.result()

File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result raise self._exception

File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run result = self.fn(*self.args, **self.kwargs)

File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/linky.py", line 41, in setup_platform client.fetch_data()

File "/srv/homeassistant/lib/python3.5/site-packages/pylinky/client.py", line 196, in fetch_data self._data[t] = self.get_data_per_period(t)

File "/srv/homeassistant/lib/python3.5/site-packages/pylinky/client.py", line 187, in get_data_per_period data = self._get_data(_MAP[_RESSOURCE][period_type], start, end)

File "/srv/homeassistant/lib/python3.5/site-packages/pylinky/client.py", line 97, in _get_data raw_res = self._session.post(DATA_URL, AttributeError: 'NoneType' object has no attribute 'post'`

This error seems different than the one exposed in #19.
Any idea?

**Comment by Pirionfr** [comment]
I think you haven't login before fetch data 0.3.1 have breaking change.

You need to do somthing like that : 
```
try:
    client.login()
    client.fetch_data()
except BaseException as exp:
    print(exp)
    return 1
finally:
    client.close_session()
print(json.dumps(client.get_data(), indent=2))
````

**Comment by CygaLV** [comment]
Hi!
I use the library inside HomeAssistant.
So I guess it takes care of the login part with the credentials set in my secrets.yaml file.
Am I wrong ?

**Comment by Pirionfr** [comment]
#22 will fix this bug

**Comment by Quentame** [comment]
Hi @CygaLV !

The Linky integration from Home Assistant has been completely redesigned and merged on 4th of September 2019, see home-assistant/core#26076

You should not have the issue right now.
Even without this I think the issue should be added in Home Assistant first.

I think we can close this issue.
