### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by pimoon** [Pirionfr/pyLinky#21]
I tried the home assistant component linky and got error so I install the pylink program with pip3 and when I do : 
`pylinky -u login - p password`
I got this following error : 
```
Traceback (most recent call last):
  File "/usr/local/bin/pylinky", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pylinky/__main__.py", line 27, in main
    print(json.dumps(client.get_data(), indent=2))
  File "/usr/local/lib/python3.5/dist-packages/pylinky/client.py", line 201, in get_data
    formatted_data[t] = self.format_data(self._data[t])
  File "/usr/local/lib/python3.5/dist-packages/pylinky/client.py", line 152, in format_data
    kwargs = {format_data: data.get('decalage') * inc}
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by pimoon** [comment]
I did nothing and it is working now...
It seems Enedis website is very often in maintenance
